services:
  app:
    image: renzojimenezb/m4_api
    container_name: nest-app
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - TZ=America/Lima

  db:
    image: postgres:14-alpine
    container_name: postgres-db
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
